# Generated by Django 4.2.5 on 2023-09-10 16:41

import django.contrib.auth.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name="номер телефона",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="id в Телеграмм"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="validation_key",
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="validation_key_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
